<?php
/**
 * Configuration file for [chargewp_bottom_horizontal_timeline] shortcode of 'Bottom Horizontal Timeline' element.
 *
 * @since 1.3
 */

use ChargewpWpbTimeline\Shortcodes\ChargeWpbShortcodeEmpty;

defined( 'ABSPATH' ) || exit;

$params = [
	[
		'type'        => 'colorpicker',
		'heading'     => esc_html__( 'Base Line Color', 'chargewp-timeline-addons-for-wpbakery' ),
		'param_name'  => 'base_line_color',
		'description' => esc_html__( 'Select custom color for the base line.', 'chargewp-timeline-addons-for-wpbakery' ),
		'value'       => '#e5e7eb',
	],
	[
		'type'        => 'chargewp_number_slider',
		'param_name'  => 'base_line_thickness',
		'heading'     => esc_html__( 'Base Line Width', 'chargewp-timeline-addons-for-wpbakery' ),
		'description' => esc_html__( 'Set the width of the base line.', 'chargewp-timeline-addons-for-wpbakery' ),
		'title'       => 'px',
		'min'         => 1,
		'max'         => 100,
		'step'        => 1,
		'value'       => 2,
	],
	[
		'type'        => 'chargewp_number_slider',
		'param_name'  => 'base_line_height',
		'heading'     => esc_html__( 'Base Line Height', 'chargewp-timeline-addons-for-wpbakery' ),
		'description' => esc_html__( 'Set the height of the base line to adjust the vertical position of it.', 'chargewp-timeline-addons-for-wpbakery' ),
		'title'       => 'px',
		'min'         => -150,
		'max'         => 150,
		'step'        => 1,
		'value'       => 25,
	],

	[
		'type'       => 'param_group',
		'group'      => esc_html__( 'Timeline Items', 'chargewp-timeline-addons-for-wpbakery' ),
		'heading'    => esc_html__( 'Timeline Items', 'chargewp-timeline-addons-for-wpbakery' ),
		'value'      => '',
		'param_name' => 'items',
		'params'     => [
			[
				'type'        => 'dropdown',
				'value'       => [
					esc_html__( 'Circle', 'chargewp-timeline-addons-for-wpbakery' ) => 'circle',
					esc_html__( 'Square', 'chargewp-timeline-addons-for-wpbakery' ) => 'square',
				],
				'heading'     => esc_html__( 'Item Type', 'chargewp-timeline-addons-for-wpbakery' ),
				'param_name'  => 'type',
				'description' => esc_html__( 'Choose item type.', 'chargewp-timeline-addons-for-wpbakery' ),
			],
			[
				'type'        => 'chargewp_number_slider',
				'param_name'  => 'size',
				'heading'     => esc_html__( 'Size', 'chargewp-timeline-addons-for-wpbakery' ),
				'description' => esc_html__( 'Set item size in pixels.', 'chargewp-timeline-addons-for-wpbakery' ),
				'title'       => 'px',
				'min'         => 0,
				'max'         => 200,
				'step'        => 1,
				'value'       => 50,
			],
			[
				'type'        => 'chargewp_number_slider',
				'param_name'  => 'border',
				'heading'     => esc_html__( 'Border', 'chargewp-timeline-addons-for-wpbakery' ),
				'description' => esc_html__( 'Set item border in pixels.', 'chargewp-timeline-addons-for-wpbakery' ),
				'title'       => 'px',
				'min'         => 0,
				'max'         => 20,
				'step'        => 1,
				'value'       => 3,
			],
			[
				'type'        => 'dropdown',
				'value'       => chargewpwpbtimeline_config( 'element-params' )['tailwind']['border_style'],
				'heading'     => esc_html__( 'Border Style', 'chargewp-timeline-addons-for-wpbakery' ),
				'param_name'  => 'border_style',
				'description' => esc_html__( 'Choose item border style.', 'chargewp-timeline-addons-for-wpbakery' ),
			],
			[
				'type'              => 'chargewp_divider',
				'param_name'        => 'divider_item_text',
				'title'             => __( 'Text', 'chargewp-timeline-addons-for-wpbakery' ),
				'title_description' => __( 'Set item text options', 'chargewp-timeline-addons-for-wpbakery' ),
				'color'             => 'black',
			],
			[
				'type'            => 'textfield',
				'wcp_group'       => true,
				'wcp_group_color' => 'black',
				'heading'         => esc_html__( 'Number', 'chargewp-timeline-addons-for-wpbakery' ),
				'param_name'      => 'number',
				'value'           => '1',
				'description'     => esc_html__( 'Enter number that will be displayed inside circle.', 'chargewp-timeline-addons-for-wpbakery' ),
				'admin_label'     => true,
			],
			[
				'type'            => 'textfield',
				'wcp_group'       => true,
				'wcp_group_color' => 'black',
				'heading'         => esc_html__( 'Title', 'chargewp-timeline-addons-for-wpbakery' ),
				'value'           => '',
				'param_name'      => 'title',
				'description'     => esc_html__( 'Enter title that will be displayed under the circle.', 'chargewp-timeline-addons-for-wpbakery' ),
			],
			[
				'type'            => 'chargewp_wysiwyg',
				'wcp_group'       => true,
				'wcp_group_color' => 'black',
				'heading'         => esc_html__( 'Info', 'chargewp-timeline-addons-for-wpbakery' ),
				'description'     => esc_html__( 'Enter info that will be displayed under the title.', 'chargewp-timeline-addons-for-wpbakery' ),
				'param_name'      => 'info',
				'value'           => '',
				'scope'           => [
					'use_menubar' => 'false',
					'use_media'   => 'false',
				],
			],
			[
				'type'              => 'chargewp_divider',
				'param_name'        => 'divider_item_color',
				'title'             => __( 'Color', 'chargewp-timeline-addons-for-wpbakery' ),
				'title_description' => __( 'Set item color options', 'chargewp-timeline-addons-for-wpbakery' ),
				'color'             => '#3e73c6',
			],
			[
				'type'        => 'colorpicker',
				'wcp_group'   => true,
				'heading'     => esc_html__( 'Circle Color', 'chargewp-timeline-addons-for-wpbakery' ),
				'param_name'  => 'circle_color',
				'description' => esc_html__( 'Select custom color for item circle.', 'chargewp-timeline-addons-for-wpbakery' ),
				'value'       => '#10b981',
			],
			[
				'type'        => 'colorpicker',
				'wcp_group'   => true,
				'heading'     => esc_html__( 'Circle Background Color', 'chargewp-timeline-addons-for-wpbakery' ),
				'param_name'  => 'circle_background_color',
				'description' => esc_html__( 'Select custom color for item circle background.', 'chargewp-timeline-addons-for-wpbakery' ),
				'value'       => '#ffffff',
			],
			[
				'type'        => 'colorpicker',
				'wcp_group'   => true,
				'heading'     => esc_html__( 'Number Color', 'chargewp-timeline-addons-for-wpbakery' ),
				'param_name'  => 'number_color',
				'description' => esc_html__( 'Select custom color for number inside circle.', 'chargewp-timeline-addons-for-wpbakery' ),
				'value'       => '#10b981',
			],
			[
				'type'        => 'colorpicker',
				'wcp_group'   => true,
				'heading'     => esc_html__( 'Title Color', 'chargewp-timeline-addons-for-wpbakery' ),
				'param_name'  => 'title_color',
				'description' => esc_html__( 'Select custom color for item circle.', 'chargewp-timeline-addons-for-wpbakery' ),
				'value'       => '#374151',
			],
			[
				'type'        => 'colorpicker',
				'wcp_group'   => true,
				'heading'     => esc_html__( 'Info', 'chargewp-timeline-addons-for-wpbakery' ),
				'param_name'  => 'info_color',
				'description' => esc_html__( 'Select custom color for item info.', 'chargewp-timeline-addons-for-wpbakery' ),
				'value'       => '#6b7280',
			],
			[
				'type'              => 'chargewp_divider',
				'param_name'        => 'divider_item_font_size',
				'title'             => __( 'Font Sizes', 'chargewp-timeline-addons-for-wpbakery' ),
				'title_description' => __( 'Set for sizes for item elements', 'chargewp-timeline-addons-for-wpbakery' ),
				'color'             => 'green',
			],
			[
				'type'            => 'chargewp_number',
				'wcp_group'       => true,
				'wcp_group_color' => 'green',
				'min'             => '1',
				'max'             => '50',
				'value'           => '16',
				'step'            => '1',
				'title'           => 'px',
				'heading'         => esc_html__( 'Number Font Size', 'chargewp-timeline-addons-for-wpbakery' ),
				'param_name'      => 'number_font_size',
				'description'     => esc_html__( 'Set font size for number text in pixels.', 'chargewp-timeline-addons-for-wpbakery' ),
			],
			[
				'type'            => 'chargewp_number',
				'wcp_group'       => true,
				'wcp_group_color' => 'green',
				'min'             => '1',
				'max'             => '50',
				'value'           => '16',
				'step'            => '1',
				'title'           => 'px',
				'heading'         => esc_html__( 'Title Font Size', 'chargewp-timeline-addons-for-wpbakery' ),
				'param_name'      => 'title_font_size',
				'description'     => esc_html__( 'Set font size for title text in pixels.', 'chargewp-timeline-addons-for-wpbakery' ),
			],
			[
				'type'            => 'chargewp_number',
				'wcp_group'       => true,
				'wcp_group_color' => 'green',
				'min'             => '1',
				'max'             => '50',
				'value'           => '13',
				'step'            => '1',
				'title'           => 'px',
				'heading'         => esc_html__( 'Info Font Size', 'chargewp-timeline-addons-for-wpbakery' ),
				'param_name'      => 'info_font_size',
				'description'     => esc_html__( 'Set font size for info text in pixels.', 'chargewp-timeline-addons-for-wpbakery' ),
			],
			[
				'type'              => 'chargewp_divider',
				'param_name'        => 'divider_item_color',
				'title'             => __( 'Font Weight', 'chargewp-timeline-addons-for-wpbakery' ),
				'title_description' => __( 'Set for weights for item elements', 'chargewp-timeline-addons-for-wpbakery' ),
				'color'             => '#7339dc',
			],
			[
				'type'            => 'chargewp_number_slider',
				'wcp_group'       => true,
				'wcp_group_color' => '#7339dc',
				'value'           => '600',
				'min'             => '0',
				'max'             => '900',
				'step'            => '100',
				'heading'         => esc_html__( 'Number Font Weight', 'chargewp-timeline-addons-for-wpbakery' ),
				'param_name'      => 'number_font_weight',
				'description'     => esc_html__( 'Set font weight for number.', 'chargewp-timeline-addons-for-wpbakery' ),
			],
			[
				'type'            => 'chargewp_number_slider',
				'wcp_group'       => true,
				'wcp_group_color' => '#7339dc',
				'value'           => '600',
				'min'             => '0',
				'max'             => '900',
				'step'            => '100',
				'heading'         => esc_html__( 'Title Font Weight', 'chargewp-timeline-addons-for-wpbakery' ),
				'param_name'      => 'title_font_weight',
				'description'     => esc_html__( 'Set font weight for a title.', 'chargewp-timeline-addons-for-wpbakery' ),
			],
		],
	],
];

return [
	'name'                    => __( 'Bottom Horizontal Timeline', 'chargewp-timeline-addons-for-wpbakery' ),
	'base'                    => 'chargewp-bottom-horizontal-timeline',
	'icon'                    => CHARGEWPWPBTIMELINE_ASSETS_URI . '/images/shortcodes/icons/bottom-horizontal-timeline.svg',
	'class'                   => 'chargewp-bottom-horizontal-timeline',
	'category'                => 'ChargeWP',
	'description'             => __( 'Bottom Horizontal Timeline. Pure CSS.', 'chargewp-timeline-addons-for-wpbakery' ),
	'php_class_name'          => ChargeWpbShortcodeEmpty::class,
	'show_settings_on_create' => true,
	'params'                  => array_merge(
		$params,
		[ vc_map_add_css_animation() ],
		chargewpwpbtimeline_config( 'element-params' )['common-bottom-params']
	),
];
